# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define() do

  create_table "comments", :force => true do |t|
    t.column "body",    :text
    t.column "post_id", :integer
  end

  create_table "posts", :force => true do |t|
    t.column "title",      :string
    t.column "created_at", :datetime
    t.column "body",       :text
  end

end
